package soundtest;

import java.awt.Color;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Igor Molodkin
 */
public class MainFrame extends javax.swing.JFrame {

    SoundTest test;
    private boolean start_flag;
    Thread say;
    Vector input;

    /**
     * Creates new form MainFrame
     */
    public MainFrame(SoundTest test) {
        this.test = test;
        input = new Vector();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ok_btn = new javax.swing.JButton();
        KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        manager.addKeyEventDispatcher(new MyDispatcher());
        start_btn = new javax.swing.JToggleButton();
        four_btn = new javax.swing.JButton();
        one_btn = new javax.swing.JButton();
        seven_btn = new javax.swing.JButton();
        two_bnt = new javax.swing.JButton();
        five_btn = new javax.swing.JButton();
        eight_btn = new javax.swing.JButton();
        three_btn = new javax.swing.JButton();
        six_btn = new javax.swing.JButton();
        nine_btn = new javax.swing.JButton();
        zero_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        answer_lbl = new javax.swing.JLabel();
        clear_btn = new javax.swing.JButton();
        order_lbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Тест на запоминание цифр");

        ok_btn.setText("OK");
        ok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_btnActionPerformed(evt);
            }
        });

        start_btn.setText("Старт");
        start_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_btnActionPerformed(evt);
            }
        });

        four_btn.setText("4");
        four_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_btnActionPerformed(evt);
            }
        });

        one_btn.setText("1");
        one_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_btnActionPerformed(evt);
            }
        });

        seven_btn.setText("7");
        seven_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_btnActionPerformed(evt);
            }
        });

        two_bnt.setText("2");
        two_bnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_bntActionPerformed(evt);
            }
        });

        five_btn.setText("5");
        five_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_btnActionPerformed(evt);
            }
        });

        eight_btn.setText("8");
        eight_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eight_btnActionPerformed(evt);
            }
        });

        three_btn.setText("3");
        three_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_btnActionPerformed(evt);
            }
        });

        six_btn.setText("6");
        six_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_btnActionPerformed(evt);
            }
        });

        nine_btn.setText("9");
        nine_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine_btnActionPerformed(evt);
            }
        });

        zero_btn.setText("0");
        zero_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_btnActionPerformed(evt);
            }
        });

        jLabel2.setText("Количество цифр:");

        jLabel3.setText("0");

        jLabel1.setText("Ответ:");

        answer_lbl.setText(" ");

        clear_btn.setText("Очистить");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        order_lbl.setText("В прямом порядке");

        jLabel6.setText("Прав.");

        jLabel7.setText("0");

        jLabel8.setText("Неправ.");

        jLabel9.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(start_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(one_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(two_bnt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(three_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clear_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(four_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(five_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(six_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(seven_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(eight_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nine_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(zero_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(ok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addComponent(order_lbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(answer_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(start_btn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(answer_lbl))
                    .addComponent(order_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(two_bnt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(three_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(one_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(four_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(five_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(six_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seven_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eight_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nine_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(zero_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clear_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void start_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_btnActionPerformed
        if (start_btn.isSelected()) {
            start_flag = true;
            say = new Thread() {
                @Override
                public void run() {
                    while (true) {
                        keys_dis();
                        test.setEnd_flag(false);
                        input.clear();
                        test.init();
                        jLabel3.setText(Integer.toString(test.getNumbers().size()));
                        if (test.isOrder()) {
                            order_lbl.setText("В прямом порядке");
                            order_lbl.setForeground(Color.black);
                        } else {
                            order_lbl.setText("В ОБРАТНОМ порядке");
                            order_lbl.setForeground(new Color(255, 116, 0));
                        }
                        test.sayAll();
                        while (!test.isEnd_flag()) {
                            try {
                                Thread.sleep(200);
                            } catch (InterruptedException ex) {
                                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        keys_en();
                        say.suspend();
                    }
                }
            };
            say.start();

        } else {
            say.stop();
        }
    }//GEN-LAST:event_start_btnActionPerformed

    private void keys_dis() {
        four_btn.setEnabled(false);
        one_btn.setEnabled(false);
        seven_btn.setEnabled(false);
        two_bnt.setEnabled(false);
        five_btn.setEnabled(false);
        eight_btn.setEnabled(false);
        three_btn.setEnabled(false);
        six_btn.setEnabled(false);
        nine_btn.setEnabled(false);
        zero_btn.setEnabled(false);
    }

    private void keys_en() {
        four_btn.setEnabled(true);
        one_btn.setEnabled(true);
        seven_btn.setEnabled(true);
        two_bnt.setEnabled(true);
        five_btn.setEnabled(true);
        eight_btn.setEnabled(true);
        three_btn.setEnabled(true);
        six_btn.setEnabled(true);
        nine_btn.setEnabled(true);
        zero_btn.setEnabled(true);
    }

    private void update_input() {
        String inp = new String();
        for (int i = 0; i < this.input.size(); i++) {
            inp = inp + Integer.toString((int) input.elementAt(i));
        }
        answer_lbl.setText(inp);
        answer_lbl.setForeground(Color.black);
    }
    private void ok_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_btnActionPerformed
        checkAnswer();
    }//GEN-LAST:event_ok_btnActionPerformed

    private void one_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_btnActionPerformed
        input.add(1);
        update_input();
    }//GEN-LAST:event_one_btnActionPerformed

    private void two_bntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_bntActionPerformed
        input.add(2);
        update_input();
    }//GEN-LAST:event_two_bntActionPerformed

    private void three_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_btnActionPerformed
        input.add(3);
        update_input();
    }//GEN-LAST:event_three_btnActionPerformed

    private void four_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_btnActionPerformed
        input.add(4);
        update_input();
    }//GEN-LAST:event_four_btnActionPerformed

    private void five_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_btnActionPerformed
        input.add(5);
        update_input();
    }//GEN-LAST:event_five_btnActionPerformed

    private void six_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_btnActionPerformed
        input.add(6);
        update_input();
    }//GEN-LAST:event_six_btnActionPerformed

    private void seven_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_btnActionPerformed
        input.add(7);
        update_input();
    }//GEN-LAST:event_seven_btnActionPerformed

    private void eight_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eight_btnActionPerformed
        input.add(8);
        update_input();
    }//GEN-LAST:event_eight_btnActionPerformed

    private void nine_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine_btnActionPerformed
        input.add(9);
        update_input();
    }//GEN-LAST:event_nine_btnActionPerformed

    private void zero_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_btnActionPerformed
        input.add(0);
        update_input();
    }//GEN-LAST:event_zero_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        input.clear();
        update_input();
    }//GEN-LAST:event_clear_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SoundTest t = new SoundTest();
                new MainFrame(t).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answer_lbl;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton eight_btn;
    private javax.swing.JButton five_btn;
    private javax.swing.JButton four_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton nine_btn;
    private javax.swing.JButton ok_btn;
    private javax.swing.JButton one_btn;
    private javax.swing.JLabel order_lbl;
    private javax.swing.JButton seven_btn;
    private javax.swing.JButton six_btn;
    private javax.swing.JToggleButton start_btn;
    private javax.swing.JButton three_btn;
    private javax.swing.JButton two_bnt;
    private javax.swing.JButton zero_btn;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the start_flag
     */
    public boolean isStart_flag() {
        return start_flag;
    }

    /**
     * @param start_flag the start_flag to set
     */
    public void setStart_flag(boolean start_flag) {
        this.start_flag = start_flag;
    }

    private void checkAnswer() {
        System.out.println("Order " + test.isOrder());
        if (test.isOrder()) {
            if (input.equals(test.getNumbers())) {
                answer_lbl.setText("ПРАВИЛЬНЫЙ");
                answer_lbl.setForeground(new Color(63, 170, 63));
                test.setCorrect(test.getCorrect() + 1);
                jLabel7.setText(Integer.toString(test.getCorrect()));
                jLabel9.setText(Integer.toString(test.getIncorrect()));
                say.resume();
            } else {
                answer_lbl.setText("НЕПРАВИЛЬНЫЙ");
                answer_lbl.setForeground(Color.RED);
                test.setIncorrect(test.getIncorrect() + 1);
                jLabel7.setText(Integer.toString(test.getCorrect()));
                jLabel9.setText(Integer.toString(test.getIncorrect()));
                System.out.println("Правильный: " + test.getNumbers().toString());
                System.out.println("Введено: " + input.toString());
                say.resume();
            }
        } else {
            Vector reverse_numbers = new Vector();
            for (int i = test.getNumbers().size() - 1; i != -1; i--) {
                reverse_numbers.add(test.getNumbers().get(i));
            }
            if (!input.equals(reverse_numbers)) {
                answer_lbl.setText("НЕПРАВИЛЬНЫЙ");
                answer_lbl.setForeground(Color.RED);
                test.setIncorrect(test.getIncorrect() + 1);
                jLabel7.setText(Integer.toString(test.getCorrect()));
                jLabel9.setText(Integer.toString(test.getIncorrect()));
                System.out.println("Обратный порядок");
                System.out.println("Правильный: " + reverse_numbers.toString());
                System.out.println("Введено: " + input.toString());
                say.resume();
            } else {
                answer_lbl.setText("ПРАВИЛЬНЫЙ");
                answer_lbl.setForeground(new Color(63, 170, 63));
                test.setCorrect(test.getCorrect() + 1);
                jLabel7.setText(Integer.toString(test.getCorrect()));
                jLabel9.setText(Integer.toString(test.getIncorrect()));
                say.resume();
            }
        }
    }

    private class MyDispatcher implements KeyEventDispatcher {

        @Override
        public boolean dispatchKeyEvent(KeyEvent e) {
            Color sys_gray = new Color(187, 187, 187); // Серый цвет
            if (e.getID() == KeyEvent.KEY_RELEASED) { // Если кнопка отпущена
                // Получение отпущенной клавиши
                String input_ch = String.valueOf(e.getKeyChar());
                if (test.isEnd_flag()) {
                    switch (input_ch) { // Окаска в серый цвет
                        case "0":
                            input.add(0);
                            update_input();
                            break;
                        case "1":
                            input.add(1);
                            update_input();
                            break;
                        case "2":
                            input.add(2);
                            update_input();
                            break;
                        case "3":
                            input.add(3);
                            update_input();
                            break;
                        case "4":
                            input.add(4);
                            update_input();
                            break;
                        case "5":
                            input.add(5);
                            update_input();
                            break;
                        case "6":
                            input.add(6);
                            update_input();
                            break;
                        case "7":
                            input.add(7);
                            update_input();
                            break;
                        case "8":
                            input.add(8);
                            update_input();
                            break;
                        case "9":
                            input.add(9);
                            update_input();
                            break;
                        case "\n":
                            checkAnswer();
                            break;
                        case "\b":
                            input.remove(input.size() - 1);
                            update_input();
                            break;
                    }
                }
            }
            return false;
        }
    }
}
